name: Publish
on:
  push:
    branches: [master, blazor-webapp]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/brixel/door-request-api
            ${{ env.REGISTRY }}/brixel/door-request-web
          tags: type=semver,pattern={{version}},value=${{ steps.gitversion.outputs.semVer }}
      - name: Build and push API
        id: docker_build_api
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: API/DoorRequest.API/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Web
        id: docker_build_web
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Web/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
